name: CI0

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Go
              run: |
                  cd tests/test3-containerize-application/docker3/backend3
                  go build .
